# Generated by Django 5.0.5 on 2024-05-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
    ]
