# Generated by Django 5.0.5 on 2024-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ussd', '0002_delete_customsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
