# Generated by Django 5.1.7 on 2025-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
