# Generated by Django 5.1.7 on 2025-03-26 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_paymenttransaction_customer_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='customer_number',
            new_name='msisdn',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='network',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
