# Generated by Django 5.1.7 on 2025-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0006_rename_customer_number_paymenttransaction_msisdn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
