# Generated by Django 5.1.7 on 2025-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0007_remove_paymenttransaction_msisdn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='nominee_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
