# Generated by Django 5.1.7 on 2025-03-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0008_customsession_created_at_customsession_order_id_and_more'),
        ('vote', '0027_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymenttransactions', to='vote.category'),
        ),
    ]
