# Generated by Django 5.1.7 on 2025-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0009_paymenttransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='event_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='payment_type',
            field=models.CharField(choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket')], default='VOTE', max_length=10),
        ),
        migrations.AddField(
            model_name='customsession',
            name='tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='event_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
