# Generated by Django 5.1.7 on 2025-05-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0011_customsession_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
