# Generated by Django 5.1.7 on 2025-05-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0012_customsession_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ('-timestamp',)},
        ),
    ]
