# Generated by Django 5.1.7 on 2025-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0013_alter_paymenttransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
