# Generated by Django 5.1.7 on 2025-05-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0015_alter_paymenttransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
