# Generated by Django 5.1.7 on 2025-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0016_alter_paymenttransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='ticket_type_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
