# Generated by Django 5.1.7 on 2025-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0019_paymenttransaction_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
