# Generated by Django 5.1.7 on 2025-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0020_paymenttransaction_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='donation_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='donation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='payment_type',
            field=models.CharField(choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket'), ('DONATION', 'Donation')], default='VOTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket'), ('DONATION', 'Donation')], max_length=10, null=True),
        ),
    ]
