# Generated by Django 5.1.7 on 2026-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_ticketpayment_qr_code_and_more'),
        ('ussd', '0022_paymenttransaction_account_name_and_more'),
        ('vote', '0037_category_percentage_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='trans_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
        migrations.AddIndex(
            model_name='customsession',
            index=models.Index(fields=['order_id'], name='ussd_custom_order_i_120b03_idx'),
        ),
        migrations.AddIndex(
            model_name='customsession',
            index=models.Index(fields=['reference'], name='ussd_custom_referen_a3e892_idx'),
        ),
        migrations.AddIndex(
            model_name='customsession',
            index=models.Index(fields=['trans_hash'], name='ussd_custom_trans_h_4a8fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order_id'], name='ussd_paymen_order_i_2145dd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='ussd_paymen_transac_884d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['trans_hash'], name='ussd_paymen_trans_h_2a8edc_idx'),
        ),
    ]
