# Generated by Django 5.1.7 on 2026-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0023_customsession_reference_customsession_trans_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='nalo_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
