# Generated by Django 5.1.7 on 2026-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0024_customsession_nalo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
