# Generated by Django 5.1.7 on 2026-05-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0025_alter_paymenttransaction_order_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customsession',
            name='ussd_custom_referen_a3e892_idx',
        ),
        migrations.RemoveIndex(
            model_name='customsession',
            name='ussd_custom_trans_h_4a8fd8_idx',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='trans_hash',
        ),
    ]
