# Generated by Django 5.1.7 on 2026-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0027_faculty_department_leveldues_studentduespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket'), ('DONATION', 'Donation'), ('DUES', 'Dues')], max_length=10, null=True),
        ),
    ]
