# Generated by Django 5.1.7 on 2026-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0028_alter_paymenttransaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='department_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='dues_academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='dues_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='dues_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customsession',
            name='faculty_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customsession',
            name='payment_type',
            field=models.CharField(choices=[('VOTE', 'Vote'), ('TICKET', 'Ticket'), ('DONATION', 'Donation'), ('DUES', 'Dues')], default='VOTE', max_length=10),
        ),
    ]
