# Generated by Django 5.1.7 on 2026-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0029_customsession_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsession',
            name='department_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
