# Generated by Django 5.1.7 on 2026-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0031_customsession_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
