# Generated by Django 5.1.7 on 2025-07-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donationcause_date_added_donationcause_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketPayment',
            new_name='DonationPayment',
        ),
    ]
