# Generated by Django 5.1.7 on 2025-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_rename_ticketpayment_donationpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcause',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='donation_img/'),
        ),
    ]
