# Generated by Django 5.1.7 on 2025-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_donationcause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcause',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcause',
            name='description8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
