# Generated by Django 4.1 on 2024-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='per_vote',
            field=models.PositiveBigIntegerField(default=0.7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
