# Generated by Django 4.1 on 2024-03-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_per_vote_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='votes',
            new_name='vote',
        ),
    ]
