# Generated by Django 4.1 on 2024-03-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
