# Generated by Django 4.1 on 2024-03-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0015_alter_nominees_can_vote'),
        ('payment', '0007_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('vote', models.IntegerField(default=0)),
                ('ref', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nominee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.nominees')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
