# Generated by Django 4.1 on 2024-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
