# Generated by Django 4.1 on 2024-04-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
