# Generated by Django 4.1 on 2024-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
