# Generated by Django 4.1 on 2024-04-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
