# Generated by Django 4.1 on 2024-04-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_nominees_sub_category'),
        ('payment', '0024_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.subcategory'),
        ),
    ]
