# Generated by Django 4.1 on 2024-04-14 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0020_alter_nominees_options_nominees_can_see_result'),
        ('payment', '0025_payment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nominees')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('total_vote', models.IntegerField(default=0, null=True)),
                ('can_vote', models.BooleanField(default=True)),
                ('can_see_result', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(null=True, verbose_name=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.subcategory')),
            ],
            options={
                'verbose_name_plural': 'nominees',
                'ordering': ('-total_vote',),
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.nominees'),
        ),
    ]
