# Generated by Django 4.1 on 2024-04-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_payment_amount'),
        ('payment', '0026_nominees_alter_payment_nominee'),
    ]

    operations = [
    ]
