# Generated by Django 4.1 on 2024-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_merge_20240414_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
