# Generated by Django 4.1 on 2024-04-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominees',
            name='category',
        ),
    ]
