# Generated by Django 4.1 on 2024-04-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_delete_nominees'),
        ('payment', '0029_remove_nominees_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.category'),
        ),
    ]
