# Generated by Django 4.1 on 2024-04-17 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0022_remove_category_content'),
        ('payment', '0032_remove_payment_content_remove_payment_nominee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nominees')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('total_vote', models.IntegerField(default=0, null=True)),
                ('can_vote', models.BooleanField(default=True)),
                ('can_see_result', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(null=True, verbose_name=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.subcategory')),
            ],
            options={
                'verbose_name_plural': 'nominees',
                'ordering': ('-total_vote',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('total_amount', models.FloatField(null=True)),
                ('vote', models.IntegerField(default=0)),
                ('ref', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.subcategory')),
                ('nominee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.nominees')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
