# Generated by Django 4.1 on 2024-04-30 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
