# Generated by Django 4.1 on 2024-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_alter_nominees_date_added_alter_nominees_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominees',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='nominees',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='date end'),
        ),
    ]
