# Generated by Django 4.1 on 2024-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4, null=True),
        ),
    ]
