# Generated by Django 5.0.5 on 2024-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
