# Generated by Django 5.0.5 on 2024-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0041_nominees_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=225, unique=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
