# Generated by Django 5.1.7 on 2025-03-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0043_remove_payment_email_remove_payment_name'),
        ('vote', '0027_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.category'),
        ),
    ]
