# Generated by Django 5.1.7 on 2025-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0044_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='price_per_vote',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=5, null=True),
        ),
    ]
