# Generated by Django 5.1.7 on 2025-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0045_nominees_price_per_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
