# Generated by Django 5.1.7 on 2025-05-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0047_alter_nominees_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='access_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
