# Generated by Django 5.1.7 on 2025-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0048_nominees_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
