# Generated by Django 5.1.7 on 2025-08-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0050_requestforpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
