# Generated by Django 4.1 on 2024-02-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nominees',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
