# Generated by Django 4.1 on 2024-02-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_category_slug_nominees_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominees',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Main_Category',
        ),
        migrations.DeleteModel(
            name='Nominees',
        ),
    ]
