# Generated by Django 4.1 on 2024-02-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominees',
            name='category',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Nominees',
        ),
    ]
