# Generated by Django 4.1 on 2024-02-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_awards_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-award',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='award',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
