# Generated by Django 4.1 on 2024-02-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_category_options_rename_name_category_award_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
