# Generated by Django 4.1 on 2024-03-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_remove_nominees_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
