# Generated by Django 4.1 on 2024-03-02 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_nominees_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
