# Generated by Django 4.1 on 2024-03-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_category_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-date',), 'verbose_name_plural': 'categories'},
        ),
    ]
