# Generated by Django 4.1 on 2024-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='can_vote',
            field=models.BooleanField(default=False),
        ),
    ]
