# Generated by Django 4.1 on 2024-04-14 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_alter_nominees_can_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
