# Generated by Django 4.1 on 2024-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_nominees_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='total_vote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
