# Generated by Django 4.1 on 2024-04-14 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_nominees_total_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
            ],
            options={
                'verbose_name_plural': 'sub categories',
                'ordering': ('-date',),
            },
        ),
    ]
