# Generated by Django 4.1 on 2024-04-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0018_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominees',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.subcategory'),
        ),
    ]
