# Generated by Django 4.1 on 2024-04-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_nominees_alter_payment_nominee'),
        ('vote', '0020_alter_nominees_options_nominees_can_see_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nominees',
        ),
    ]
