# Generated by Django 4.1 on 2024-04-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_delete_nominees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
    ]
