# Generated by Django 5.0.5 on 2024-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0025_alter_category_date_added_alter_category_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='blog-img')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'blogs',
                'ordering': ('-date_added',),
            },
        ),
    ]
