# Generated by Django 5.1.7 on 2025-05-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0027_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='access_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
