# Generated by Django 5.1.7 on 2025-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0029_subcategory_can_check_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
