# Generated by Django 5.1.7 on 2025-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0030_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nomination_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
