# Generated by Django 5.1.7 on 2025-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0031_category_nomination_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nomination_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
