# Generated by Django 5.1.7 on 2025-07-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0032_category_nomination_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nomination_start_date',
        ),
    ]
