# Generated by Django 5.1.7 on 2025-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0035_category_close_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bulk_voting_options',
            field=models.JSONField(blank=True, default=list, help_text="JSON list of bulk voting options in format [{'amount': X, 'votes': Y}]", null=True),
        ),
    ]
