# Generated by Django 5.1.7 on 2025-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0036_category_bulk_voting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='percentage_earned',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage that the Award will earn (e.g., 80.00 for 80%)', max_digits=5),
        ),
    ]
