# Generated by Django 5.1.7 on 2026-05-12 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0037_category_percentage_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('update_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('deadline', 'Deadline')], default='info', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='vote.category')),
            ],
            options={
                'verbose_name_plural': 'category updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
