# Generated by Django 5.1.7 on 2025-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
