# Generated by Django 5.1.7 on 2025-10-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_options_remove_candidate_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
