# Generated by Django 4.1 on 2024-03-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
