# Generated by Django 4.1 on 2024-03-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_nominees_slug'),
        ('register', '0003_register_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.category'),
        ),
    ]
