# Generated by Django 4.1 on 2024-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_register_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
