# Generated by Django 4.1 on 2024-03-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='slug',
        ),
    ]
