# Generated by Django 4.1 on 2024-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_register_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='register_img'),
        ),
    ]
