# Generated by Django 4.1 on 2024-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
