# Generated by Django 5.1.7 on 2025-06-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_register_category_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('event_description', models.TextField()),
                ('event_type', models.CharField(choices=[('REALITY', 'Reality Show'), ('AWARDS', 'Awards'), ('ELECTIONS', 'Elections'), ('QUIZ', 'Quiz'), ('OTHER', 'Other')], max_length=20)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
