# Generated by Django 5.1.7 on 2025-04-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketpayment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpayment',
            name='total_amount',
        ),
    ]
