# Generated by Django 5.1.7 on 2025-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_event_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
