# Generated by Django 5.1.7 on 2025-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_event_available_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
