# Generated by Django 5.1.7 on 2025-05-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_event_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
