# Generated by Django 5.1.7 on 2025-09-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_delete_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpayment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='ticketpayment',
            name='qr_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpayment',
            name='qr_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketpayment',
            name='qr_verified',
            field=models.BooleanField(default=False),
        ),
    ]
